services:
  user_database:
    image: postgres:17-alpine
    restart: unless-stopped

    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - user-db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d users"]
      interval: 10s
      timeout: 5s
      retries: 5


  portfolio_database:
    image: postgres:17-alpine
    restart: unless-stopped

    environment:
      POSTGRES_DB: portfolios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PORTFOLIO_DB_PASSWORD}

    ports:
      - "5434:5432"

    volumes:
      - portfolio-db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d portfolios"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  user-db-data:
  portfolio-db-data: